# Generated by Django 3.2.4 on 2021-06-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_alter_employer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
