# Generated by Django 3.2.4 on 2021-06-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_alter_employer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
